[build]
backend = "cd backend && npm install && npm run build"
frontend = "cd frontend && npm install && npm run build"

[start]
backend = "cd backend && npm start"
frontend = "cd frontend && npm run start"
